---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-test
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx-test
      template:
        metadata:
          labels:
            app: nginx-test
        spec:
          containers:
          - image: nginx:latest
            name: nginx-test
            ports:
            - containerPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testing-api-virtualservice
  namespace: default
spec:
  hosts:
    - *
  gateways:
    - test-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: nginx-api-service
          port:
            number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtualservice
  namespace: default
spec:
  hosts:
  - *
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: nginx-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      protocol: HTTP
      name: http
    hosts:
    - *